import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {publicContent,publicMetadata,canonicalBase,readSeo,documentMeta} from "@/lib/seo";
import {sanitizeEducationHtml} from "@/lib/education";
import JsonLd from "@/components/JsonLd";
import Sponsored from "@/components/Sponsored";
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;if(!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug))return {robots:{index:false,follow:false}};const article=await publicContent('article',slug);if(!article)return {title:'Artikel tidak ditemukan',robots:{index:false,follow:false}};const metadata=await publicMetadata('/artikel/'+slug,article.title,article.excerpt,article.cover_url??undefined);return {...metadata,openGraph:{...metadata.openGraph,type:'article',publishedTime:article.published_at}};}
export default async function Article({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug))notFound();const a=await publicContent('article',slug);if(!a)notFound();const base=canonicalBase(await readSeo()),m=await documentMeta("/artikel/"+slug),canonical=m.canonical||(base?base+"/artikel/"+slug:null);return <main className="mx-auto my-8 max-w-4xl px-5"><Link href="/" className="text-sm text-purple-800">← Beranda</Link><article className="mt-6 rounded-[36px] bg-white p-6 shadow-soft sm:p-10"><p className="text-xs text-muted">{a.category}{a.is_premium?' · Premium':''}</p><h1 className="mt-4 text-3xl font-medium">{a.title}</h1><p className="mt-4 text-sm leading-relaxed text-muted">{a.excerpt}</p>{a.cover_url&&<img src={a.cover_url} alt={a.title} className="mt-6 max-h-96 w-full rounded-[28px] object-cover"/>}{a.content?<div className="mt-6 text-sm leading-relaxed [&_p]:mb-4 [&_h2]:my-5 [&_h2]:text-2xl [&_ul]:list-disc [&_ul]:pl-5" dangerouslySetInnerHTML={{__html:sanitizeEducationHtml(a.content)}}/>:<div className="mt-6 rounded-2xl bg-lilac p-5"><p className="text-sm">Bacaan lengkap tersedia untuk anggota Premium.</p><Link href="/app/edukasi" className="btn btn-brand mt-4 text-xs">Buka edukasi →</Link></div>}</article><JsonLd data={{'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.excerpt,datePublished:a.published_at,inLanguage:'id-ID',...(canonical?{url:canonical,mainEntityOfPage:canonical}:{}),...(a.cover_url?{image:[a.cover_url]}:{})}}/><Sponsored placement="artikel"/></main>;}
