"use server";
import {canonicalBase,readSeo} from "@/lib/seo";
import {requireAdmin} from "@/lib/admin";
import {revalidatePath} from "next/cache";
import {validateSeo,validateMeta,safeSource,redirectDestination,type SeoSettings,type SeoMeta,type SeoRedirect} from "@/lib/seo-schema";
async function mutate(kind:string,payload:Record<string,unknown>){const {supabase}=await requireAdmin();const {error}=await supabase.rpc('admin_save_marketing',{kind,payload});if(error)return {error:error.code==='23505'?'Alamat asal sudah digunakan.':'Belum tersimpan. Periksa migration, pilihan gambar, dan pastikan redirect tidak membentuk putaran.'};revalidatePath('/','layout');return {error:null};}
export async function saveGlobalSeo(value:SeoSettings){await requireAdmin();try{const error=validateSeo(value);if(error)return {error};return await mutate('seo_global',{...value,canonicalBase:value.canonicalBase.replace(/\/$/,'')});}catch{return {error:'Pengaturan SEO tidak valid.'};}}
export async function saveDocumentSeo(path:string,meta:SeoMeta){await requireAdmin();try{const error=validateMeta(meta);if(error)return {error};if(typeof path!=='string'||path.length>200)return {error:'Halaman tidak valid.'};return await mutate('seo_document',{path,meta});}catch{return {error:'Metadata tidak valid.'};}}
export async function saveSeoRedirect(value:SeoRedirect){await requireAdmin();if(!value||typeof value.source!=='string'||typeof value.destination!=='string'||!safeSource(value.source)||!redirectDestination(value.destination)||value.source===value.destination||typeof value.active!=='boolean'||typeof value.id!=='string'||(value.id&&!/^[0-9a-f-]{36}$/i.test(value.id)))return {error:'Gunakan alamat asal lokal dan tujuan lokal atau HTTPS yang berbeda. Route sistem tidak boleh dialihkan.'};const base=canonicalBase(await readSeo());if(base&&value.destination.startsWith("https://")){const dest=new URL(value.destination);if(dest.origin===base){if(dest.search)return {error:"Gunakan tujuan lokal tanpa query untuk redirect di situs sendiri."};value={...value,destination:dest.pathname};if(value.source===value.destination)return {error:"Tujuan redirect harus berbeda dari alamat asal."};}}return mutate('redirect',{...value});}
export async function deleteSeoRedirect(id:string){await requireAdmin();if(!/^[0-9a-f-]{36}$/i.test(id))return {error:'Redirect tidak valid.'};return mutate('redirect_delete',{id});}
