"use client";
import {useState,useTransition,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {saveReview,removeReview} from "@/app/app/review/actions";
import type {OwnReview} from "@/app/app/review/types";
const statuses:Record<string,string>={published:"Tayang",pending:"Menunggu moderasi",hidden:"Disembunyikan admin",removed:"Dihapus dari publik oleh admin"};
export default function ReviewEditor({own}:{own:OwnReview|null}){
  const [rating,setRating]=useState(own?.rating??5),[title,setTitle]=useState(own?.title??""),[body,setBody]=useState(own?.body??""),[message,setMessage]=useState(""),[confirm,setConfirm]=useState(false);
  const [pending,startTransition]=useTransition();const router=useRouter();
  function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!title.trim()||title.trim().length>120||!body.trim()||body.trim().length>2000||!Number.isInteger(rating)||rating<1||rating>5){setMessage("Isi judul, ulasan, dan bintang 1–5, ya.");return;}startTransition(async()=>{try{const result=await saveReview({rating,title,body});setMessage(result.error??"Ulasan tersimpan. Status terbarunya akan tampil di bawah judul form.");if(!result.error)router.refresh();}catch{setMessage("Ulasan belum tersimpan. Coba lagi sebentar, ya.");}});}
  function remove(){startTransition(async()=>{try{const result=await removeReview();setMessage(result.error??"Ulasan terhapus.");if(!result.error)router.refresh();}catch{setMessage("Ulasan belum terhapus.");}});}
  return <section className="mt-8 rounded-[36px] bg-white p-5 shadow-soft sm:p-8"><h2 className="text-xl font-medium">{own?"Edit ulasanmu":"Bagikan pengalamanmu"}</h2>{own&&<div className="mt-3 rounded-2xl bg-lilac p-4 text-xs text-purple-800"><p>Status: {statuses[own.status]??own.status}</p>{own.note&&<p className="mt-2">Catatan admin: {own.note}</p>}</div>}<form onSubmit={save} className="mt-5"><fieldset disabled={pending} className="space-y-5"><div><label htmlFor="review-rating" className="block text-sm">Bintang</label><select id="review-rating" value={rating} onChange={event=>setRating(Number(event.target.value))} className="mt-2 rounded-full border border-[#EADFF2] px-5 py-3 text-sm">{[5,4,3,2,1].map(value=><option key={value} value={value}>{value} ★</option>)}</select></div><div><label htmlFor="review-title" className="text-sm">Judul</label><input id="review-title" required maxLength={120} value={title} onChange={event=>setTitle(event.target.value)} className="mt-2 w-full rounded-full border border-[#EADFF2] px-5 py-3 text-sm focus:outline-purple-600"/></div><div><label htmlFor="review-body" className="text-sm">Ulasanmu</label><textarea id="review-body" required maxLength={2000} rows={4} value={body} onChange={event=>setBody(event.target.value)} placeholder="Apa yang membantumu? Apa yang bisa kami perbaiki?" className="mt-2 w-full rounded-2xl border border-[#EADFF2] p-4 text-sm focus:outline-purple-600"/><p className="text-right text-xs text-muted">{body.length}/2.000 karakter</p></div><button type="submit" className="btn btn-brand text-sm">{pending?"Memproses…":"Simpan ulasan →"}</button></fieldset></form>{own&&<div className="mt-4">{confirm?<div className="rounded-2xl bg-peach p-4"><p className="text-sm">Hapus ulasanmu? Tindakan ini tidak bisa dibatalkan.</p><div className="mt-3 flex gap-2"><button disabled={pending} onClick={remove} className="btn btn-ghost text-xs">Ya, hapus</button><button disabled={pending} onClick={()=>setConfirm(false)} className="btn btn-ghost text-xs">Batal</button></div></div>:<button disabled={pending} onClick={()=>setConfirm(true)} className="btn btn-ghost text-xs">Hapus ulasanku</button>}</div>}<p role="status" className="mt-4 text-sm text-purple-800">{message}</p></section>;
}
