"use client";
import {useState,useTransition} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {voteReview,reportReview} from "@/app/app/review/actions";
import type {PublicReview} from "@/app/app/review/types";
function ReviewItem({review,authenticated}:{review:PublicReview;authenticated:boolean}){
  const [report,setReport]=useState(false),[reason,setReason]=useState("spam"),[message,setMessage]=useState("");const [pending,startTransition]=useTransition();const router=useRouter();
  function run(kind:"vote"|"report"){startTransition(async()=>{try{const result=kind==="vote"?await voteReview(review.id,!review.voted):await reportReview(review.id,reason);setMessage(result.error??(kind==="report"?"Laporan terkirim. Terima kasih sudah menjaga ruang ini.":"Vote diperbarui."));if(!result.error){setReport(false);router.refresh();}}catch{setMessage("Belum tersimpan. Coba lagi sebentar, ya.");}});}
  return <article className="rounded-[36px] bg-white p-5 shadow-soft sm:p-7"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-medium text-purple-800">{review.name}</p><span aria-label={`${review.rating} dari 5 bintang`} className="text-sm tracking-widest text-magenta-600">{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</span></div><p className="mt-2 text-[10px] text-muted">{new Intl.DateTimeFormat("id-ID",{dateStyle:"long",timeZone:"UTC"}).format(new Date(`${review.day}T00:00:00Z`))}</p><h3 className="mt-4 break-words text-lg font-medium">{review.title}</h3><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-relaxed text-muted">{review.body}</p><div className="mt-5 flex flex-wrap gap-2">{authenticated?<><button disabled={pending} aria-pressed={review.voted} onClick={()=>run("vote")} className={`btn text-xs disabled:opacity-60 ${review.voted?"btn-brand":"btn-ghost"}`}>Membantu · {review.helpful}</button><button disabled={pending} aria-expanded={report} onClick={()=>setReport(!report)} className="btn btn-ghost text-xs">Laporkan</button></>:<><Link href="/app/review" className="btn btn-ghost text-xs">Membantu · {review.helpful}</Link><Link href="/app/review" className="btn btn-ghost text-xs">Masuk untuk melaporkan</Link></>}</div>{report&&<div className="mt-4 rounded-2xl bg-peach p-4"><label className="text-xs">Alasan laporan<select value={reason} disabled={pending} onChange={event=>setReason(event.target.value)} className="ml-3 rounded-full border border-[#EADFF2] p-2 text-xs"><option value="spam">Spam</option><option value="sara">SARA</option><option value="lainnya">Lainnya</option></select></label><button disabled={pending} onClick={()=>run("report")} className="btn btn-ghost ml-2 mt-2 text-xs">Kirim laporan</button></div>}<p role="status" className="mt-3 text-xs text-purple-800">{message}</p></article>;
}
export default function ReviewBoard({reviews,authenticated,loadError}:{reviews:PublicReview[];authenticated:boolean;loadError:boolean}){
  const [stars,setStars]=useState(0),[sort,setSort]=useState("newest");
  const distribution=[5,4,3,2,1].map(rating=>({rating,count:reviews.filter(review=>review.rating===rating).length}));
  const average=reviews.length?reviews.reduce((sum,review)=>sum+review.rating,0)/reviews.length:0;
  const filtered=reviews.filter(review=>stars===0||review.rating===stars).sort((a,b)=>sort==="helpful"?b.helpful-a.helpful:0);
  if(loadError)return <p role="alert" className="mt-8 rounded-2xl bg-peach p-5 text-sm">Ulasan belum bisa dimuat. Coba muat ulang sebentar lagi, ya.</p>;
  return <section aria-labelledby="review-list-title" className="mt-10"><h2 id="review-list-title" className="text-xl font-medium">Ulasan yang tayang</h2><div className="mt-5 grid gap-6 rounded-[36px] bg-lilac p-6 sm:grid-cols-[1fr_2fr]"><div><p className="text-5xl font-semibold text-purple-800">{reviews.length?average.toLocaleString("id-ID",{maximumFractionDigits:1}):"—"}<span className="text-lg font-normal text-muted"> / 5</span></p><p className="mt-3 text-xs text-muted">{reviews.length} ulasan</p></div><div className="space-y-2">{distribution.map(({rating,count})=><div key={rating} className="flex items-center gap-3 text-xs text-purple-800"><span className="w-7">{rating} ★</span><div aria-hidden="true" className="h-2 flex-1 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full" style={{width:`${reviews.length?count/reviews.length*100:0}%`,background:"var(--grad-brand)"}}/></div><span className="w-8 text-right">{count}</span></div>)}</div></div><div role="group" aria-label="Filter bintang" className="mt-6 flex flex-wrap gap-2">{[0,5,4,3,2,1].map(value=><button key={value} aria-pressed={stars===value} onClick={()=>setStars(value)} className={`btn text-xs ${stars===value?"btn-brand":"btn-ghost"}`}>{value===0?"Semua":`${value} ★`}</button>)}<label className="sr-only" htmlFor="review-sort">Urutkan ulasan</label><select id="review-sort" value={sort} onChange={event=>setSort(event.target.value)} className="rounded-full border border-[#EADFF2] bg-white px-4 py-2 text-xs"><option value="newest">Terbaru</option><option value="helpful">Paling membantu</option></select></div><p role="status" className="my-4 text-xs text-muted">{filtered.length} ulasan sesuai filter</p>{filtered.length?<div className="space-y-5">{filtered.map(review=><ReviewItem key={review.id} review={review} authenticated={authenticated}/>)}</div>:<p className="rounded-[24px] bg-white p-6 text-sm text-muted">Belum ada ulasan untuk pilihan ini.</p>}</section>;
}
