import type {PageBlock} from "./cms";
export const DEFAULT_HOME_BLOCKS:PageBlock[]=[
  {
    "id": "home-hero",
    "type": "hero",
    "title": "Tempat aman untuk semua ceritamu.",
    "eyebrow": "RUANG UNTUK MENJADI DIRIMU",
    "text": "",
    "buttonText": "Mulai Bercerita",
    "buttonHref": "/masuk",
    "imageUrl": "/images/meditasi.jpg",
    "imageAlt": "Perempuan menikmati waktu tenang di antara tanaman",
    "secondaryImageUrl": "/images/laptop.jpg",
    "visualLabel": "BERCERITA · BERTUMBUH · BERSAMA",
    "aboutTitle": "Setiap rasa punya cerita.",
    "aboutText": "Kadang, kita hanya butuh tempat untuk didengar. Mulai dari apa pun yang sedang kamu rasakan.",
    "aboutLabel": "Tentang {{site}}",
    "aboutButtonText": "Kenali {{site}}",
    "aboutButtonHref": "#fitur",
    "youtubeUrl": "",
    "html": "",
    "items": [],
    "useSiteChips": false
  },
  {
    "id": "home-features",
    "type": "features",
    "title": "",
    "eyebrow": "",
    "text": "",
    "buttonText": "",
    "buttonHref": "/masuk",
    "imageUrl": "",
    "imageAlt": "",
    "secondaryImageUrl": "",
    "visualLabel": "",
    "aboutTitle": "",
    "aboutText": "",
    "aboutLabel": "",
    "aboutButtonText": "",
    "aboutButtonHref": "#fitur",
    "youtubeUrl": "",
    "html": "",
    "items": [
      {
        "title": "Ruang Cerita Anonim",
        "text": "Ada ruang untuk setiap rasa. Ceritakan tanpa takut dihakimi.",
        "label": "Ceritamu berarti",
        "symbol": "♡",
        "imageUrl": "",
        "imageAlt": "",
        "href": "/masuk"
      },
      {
        "title": "Mood Tracker",
        "text": "Kenali perasaanmu, satu hari kecil dalam satu waktu.",
        "label": "Apa kabarmu?",
        "symbol": "☀",
        "imageUrl": "",
        "imageAlt": "",
        "href": "/masuk"
      },
      {
        "title": "Journaling",
        "text": "Tuangkan isi kepala. Temukan ruang tenang untuk dirimu.",
        "label": "Catatan untuk diri",
        "symbol": "✎",
        "imageUrl": "",
        "imageAlt": "",
        "href": "/masuk"
      },
      {
        "title": "Konten Edukasi",
        "text": "Belajar memahami diri lewat bacaan dan video ringan.",
        "label": "Tumbuh bersama",
        "symbol": "✿",
        "imageUrl": "",
        "imageAlt": "",
        "href": "/masuk"
      }
    ],
    "useSiteChips": false
  },
  {
    "id": "home-pricing",
    "type": "pricing",
    "title": "Ruang tumbuh untuk setiap cerita",
    "eyebrow": "SESUAI LANGKAHMU",
    "text": "",
    "buttonText": "",
    "buttonHref": "/masuk",
    "imageUrl": "",
    "imageAlt": "",
    "secondaryImageUrl": "",
    "visualLabel": "",
    "aboutTitle": "",
    "aboutText": "",
    "aboutLabel": "",
    "aboutButtonText": "",
    "aboutButtonHref": "#fitur",
    "youtubeUrl": "",
    "html": "",
    "items": [],
    "useSiteChips": false
  },
  {
    "id": "home-testimonials",
    "type": "testimonials",
    "title": "Apa kata mereka",
    "eyebrow": "CERITA DARI TEMAN KITA",
    "text": "Setiap perjalanan berbeda. Kamu boleh berjalan dengan ritmemu sendiri.",
    "buttonText": "",
    "buttonHref": "/masuk",
    "imageUrl": "",
    "imageAlt": "",
    "secondaryImageUrl": "",
    "visualLabel": "",
    "aboutTitle": "",
    "aboutText": "",
    "aboutLabel": "",
    "aboutButtonText": "",
    "aboutButtonHref": "#fitur",
    "youtubeUrl": "",
    "html": "",
    "items": [],
    "useSiteChips": false
  },
  {
    "id": "home-chips",
    "type": "chips",
    "title": "Bergabung dengan gerakan",
    "eyebrow": "",
    "text": "Langkah kecilmu berarti. Mari tumbuh bersama.",
    "buttonText": "",
    "buttonHref": "/masuk",
    "imageUrl": "",
    "imageAlt": "",
    "secondaryImageUrl": "",
    "visualLabel": "",
    "aboutTitle": "",
    "aboutText": "",
    "aboutLabel": "",
    "aboutButtonText": "",
    "aboutButtonHref": "#fitur",
    "youtubeUrl": "",
    "html": "",
    "items": [],
    "useSiteChips": true
  },
  {
    "id": "home-cta",
    "type": "cta",
    "title": "Siap mulai\n perjalananmu?",
    "eyebrow": "",
    "text": "Ada tempat untuk ceritamu di sini.",
    "buttonText": "Daftar Gratis",
    "buttonHref": "/masuk",
    "imageUrl": "",
    "imageAlt": "",
    "secondaryImageUrl": "",
    "visualLabel": "",
    "aboutTitle": "",
    "aboutText": "",
    "aboutLabel": "",
    "aboutButtonText": "",
    "aboutButtonHref": "#fitur",
    "youtubeUrl": "",
    "html": "",
    "items": [],
    "useSiteChips": false
  }
];
