export type SeoMeta={title:string;description:string;canonical:string;ogImage:string;noindex:boolean};
export type SeoSettings={titleTemplate:string;description:string;ogImage:string;canonicalBase:string;googleVerification:string;bingVerification:string;analyticsId:string;robots:string};
export type SeoDocument={path:string;title:string;kind:"page"|"article";published:boolean;heading:boolean;images:number;altImages:number;meta:SeoMeta};
export type SeoRedirect={id:string;source:string;destination:string;active:boolean};
export const EMPTY_META:SeoMeta={title:"",description:"",canonical:"",ogImage:"",noindex:false};
export const DEFAULT_SEO:SeoSettings={titleTemplate:"%s | CeritaKita",description:"Tempat aman untuk bercerita, mencatat mood, menulis jurnal, dan belajar kesehatan mental.",ogImage:"",canonicalBase:"",googleVerification:"",bingVerification:"",analyticsId:"",robots:"User-agent: *\nAllow: /\nDisallow: /app\nDisallow: /admin\nDisallow: /auth\n"};
export function https(value:string){try{const u=new URL(value);return u.protocol==="https:"&&!u.username&&!u.password&&!u.hash;}catch{return false;}}
export function localPath(v:string){return /^\/(?:[a-z0-9-]+\/)*[a-z0-9-]*$/.test(v)&&!v.startsWith("//")&&v.length<=180;}
export function safeSource(v:string){return localPath(v)&&v!=="/"&&!/^\/(app|admin|api|auth|masuk|sponsor)(\/|$)/.test(v);}
export function redirectDestination(v:string){return localPath(v)||https(v);}
export function validRobots(v:string){if(v.length>10000)return false;return v.split(/\r?\n/).every(line=>{const s=line.trim();if(!s||s.startsWith("#"))return true;const m=s.match(/^(User-agent|Allow|Disallow|Crawl-delay|Sitemap|Host):\s*(.*?)\s*$/i);if(!m)return false;const key=m[1].toLowerCase(),value=m[2];if(key==='sitemap'||key==='host')return https(value);if(key==='crawl-delay')return /^\d+(\.\d+)?$/.test(value)&&Number(value)<=3600;if(key==='user-agent')return /^[\w*.-]+$/.test(value);return !/[\r\n]/.test(value)&&(!value||value.startsWith('/'))&&!(key==='allow'&&/^\/(app|admin|auth)(\/|\*|$)/.test(value));});}
export function validateSeo(s:SeoSettings){if(!s||typeof s!=="object"||Object.values(s).some(v=>typeof v!=="string"))return "Pengaturan SEO tidak valid.";if(!s.titleTemplate.includes('%s')||s.titleTemplate.length>150)return "Template judul harus berisi %s, maksimal 150 karakter.";if(s.description.length>500||s.ogImage.length>2048||(s.ogImage&&!https(s.ogImage)))return "Deskripsi atau gambar OG tidak valid.";if(s.canonicalBase){if(!https(s.canonicalBase))return "Canonical base harus berupa URL HTTPS.";const u=new URL(s.canonicalBase);if(u.search||u.pathname!=='/')return "Canonical base cukup domain situs, tanpa path atau query.";}if(!/^(|G-[A-Z0-9]{4,30})$/.test(s.analyticsId))return "Gunakan ID Google Analytics 4, misalnya G-XXXXXXXXXX.";if([s.googleVerification,s.bingVerification].some(v=>!/^[-\w]{0,200}$/.test(v)))return "Isi kode verifikasi saja, tanpa tag HTML.";if(!validRobots(s.robots))return "Robots mendukung User-agent, Allow, Disallow, Crawl-delay, Sitemap, Host, dan komentar. Area privat harus tetap diblokir.";return null;}
export function parseMeta(v:unknown):SeoMeta{const o=v&&typeof v==='object'?v as Record<string,unknown>:{};return {title:typeof o.title==='string'?o.title.slice(0,200):'',description:typeof o.description==='string'?o.description.slice(0,500):'',canonical:typeof o.canonical==='string'&&https(o.canonical)?o.canonical:'',ogImage:typeof o.ogImage==='string'&&https(o.ogImage)?o.ogImage:'',noindex:o.noindex===true};}
export function validateMeta(v:SeoMeta){if(!v||typeof v!=='object'||['title','description','canonical','ogImage'].some(k=>typeof v[k as keyof SeoMeta]!=='string')||typeof v.noindex!=='boolean')return "Metadata tidak valid.";if(v.title.length>200||v.description.length>500||v.canonical.length>2048||v.ogImage.length>2048)return "Metadata terlalu panjang.";if((v.canonical&&!https(v.canonical))||(v.ogImage&&!https(v.ogImage)))return "Canonical dan gambar OG harus URL HTTPS.";return null;}
export function seoScore(d:Pick<SeoDocument,'heading'|'images'|'altImages'>,m:SeoMeta){return (m.title.length>=30&&m.title.length<=60?25:0)+(m.description.length>=120&&m.description.length<=160?25:0)+(d.heading?20:0)+(d.images===0||d.altImages===d.images?15:0)+(m.ogImage?15:0);}
export function robotsRules(text:string){type Rule={userAgent:string[];allow:string[];disallow:string[];crawlDelay?:number};const rules:Rule[]=[];const sitemap:string[]=[];let current:Rule|null=null,hasDirective=false,host:string|undefined;for(const line of text.split(/\r?\n/)){const m=line.trim().match(/^([\w-]+):\s*(.*?)\s*$/);if(!m)continue;const k=m[1].toLowerCase(),v=m[2];if(k==='user-agent'){if(!current||hasDirective){current={userAgent:[],allow:[],disallow:[]};rules.push(current);hasDirective=false;}current.userAgent.push(v);}else if(k==='sitemap'&&https(v))sitemap.push(v);else if(k==='host'&&https(v))host=v;else if(current){if(k==='allow')current.allow.push(v);if(k==='disallow')current.disallow.push(v);if(k==='crawl-delay')current.crawlDelay=Number(v);hasDirective=true;}}if(!rules.length)rules.push({userAgent:['*'],allow:['/'],disallow:[]});if(!rules.some(r=>r.userAgent.includes('*')))rules.push({userAgent:['*'],allow:[],disallow:[]});for(const r of rules){r.allow=r.allow.filter(v=>!/^\/(app|admin|auth)(\/|\*|$)/.test(v));r.disallow=[...new Set([...r.disallow,'/app','/admin','/auth'])];}return {rules,sitemap,host};}
