import "server-only";
import {cache} from "react";
import type {Metadata} from "next";
import {publicReviewClient} from "./reviews";
import {readSiteSettings} from "./site-settings";
import {DEFAULT_SEO,parseMeta,https,type SeoSettings,type SeoMeta} from "./seo-schema";
export const readSeo=cache(async():Promise<SeoSettings>=>{const c=publicReviewClient();if(!c)return {...DEFAULT_SEO};const {data}=await c.from('seo_settings').select('settings').eq('id',1).maybeSingle();const value=data?.settings;if(!value||typeof value!=='object')return {...DEFAULT_SEO};return {...DEFAULT_SEO,...Object.fromEntries(Object.entries(value).filter(([k,v])=>k in DEFAULT_SEO&&typeof v==='string'))};});
export function canonicalBase(s:SeoSettings){if(s.canonicalBase&&https(s.canonicalBase))return new URL(s.canonicalBase).origin;const configured=process.env.NEXT_PUBLIC_SITE_URL;if(configured&&https(configured))return new URL(configured).origin;return null;}
export async function documentMeta(path:string):Promise<SeoMeta>{const c=publicReviewClient();if(!c)return parseMeta(null);const {data}=await c.from('seo_documents').select('meta').eq('path',path).maybeSingle();return parseMeta(data?.meta);}
export async function publicMetadata(path:string,title:string,description?:string,image?:string):Promise<Metadata>{const [s,m]=await Promise.all([readSeo(),documentMeta(path)]);const base=canonicalBase(s),canonical=m.canonical||(base?base+path:undefined),desc=m.description||description||s.description,og=m.ogImage||image||s.ogImage;const expanded=s.titleTemplate.replaceAll('%s',m.title||title);return {title:{absolute:expanded},description:desc,alternates:canonical?{canonical}:undefined,robots:{index:!m.noindex,follow:!m.noindex},openGraph:{type:'website',title:expanded,description:desc,...(canonical?{url:canonical}:{}),...(og?{images:[{url:og}]}:{})},twitter:{card:'summary_large_image',title:expanded,description:desc,...(og?{images:[og]}:{})}};}
export async function globalMetadata():Promise<Metadata>{const [s,site]=await Promise.all([readSeo(),readSiteSettings()]);const base=canonicalBase(s);return {title:{default:s.titleTemplate.replaceAll('%s',site.name),template:s.titleTemplate},description:s.description,...(base?{metadataBase:new URL(base)}:{}),verification:{...(s.googleVerification?{google:s.googleVerification}:{}),...(s.bingVerification?{other:{'msvalidate.01':s.bingVerification}}:{})},icons:{icon:site.faviconUrl,shortcut:site.faviconUrl},openGraph:{siteName:site.name,locale:'id_ID',...(s.ogImage?{images:[s.ogImage]}:{})},twitter:{card:'summary_large_image'}};}
export type PublicArticle={id:string;slug:string;title:string;excerpt:string;content:string|null;cover_url:string|null;category:string;is_premium:boolean;published_at:string};
export type PublicVideo={id:string;title:string;description:string;youtube_id:string|null;category:string;is_premium:boolean;published_at:string};
export function publicContent(kind:'article',value:string):Promise<PublicArticle|null>;
export function publicContent(kind:'video',value:string):Promise<PublicVideo|null>;
export async function publicContent(kind:'article'|'video',value:string):Promise<PublicArticle|PublicVideo|null>{const c=publicReviewClient();if(!c)return null;if(kind==='article'){const {data}=await c.from('seo_articles').select('id,slug,title,excerpt,content,cover_url,category,is_premium,published_at').eq('slug',value).maybeSingle();return data as PublicArticle|null;}const {data}=await c.from('seo_videos').select('id,title,description,youtube_id,category,is_premium,published_at').eq('id',value).maybeSingle();return data as PublicVideo|null;}
export async function siteJsonLd(){const [seo,site]=await Promise.all([readSeo(),readSiteSettings()]);const base=canonicalBase(seo);if(!base)return [];return [{'@context':'https://schema.org','@type':'Organization','@id':base+'/#organization',name:site.name,url:base,logo:new URL(site.logoUrl,base).href}, {'@context':'https://schema.org','@type':'WebSite','@id':base+'/#website',name:site.name,url:base,inLanguage:'id-ID',publisher:{'@id':base+'/#organization'}}];}
