"use client";
import {useState,type ReactNode} from "react";
export type Column<T>={key:string;label:string;render:(row:T)=>ReactNode};
export default function DataTable<T>({rows,columns,rowKey,searchText,filterText,filters=[],empty="Belum ada data.",pageSize=10}:{rows:T[];columns:Column<T>[];rowKey:(row:T)=>string;searchText:(row:T)=>string;filterText?:(row:T)=>string;filters?:{value:string;label:string}[];empty?:string;pageSize?:number}){
 const [search,setSearch]=useState("");const [filter,setFilter]=useState("");const [page,setPage]=useState(1);
 const filtered=rows.filter(row=>searchText(row).toLocaleLowerCase("id-ID").includes(search.trim().toLocaleLowerCase("id-ID"))&&(!filter||filterText?.(row)===filter));
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const current=Math.min(page,pages);const visible=filtered.slice((current-1)*pageSize,current*pageSize);
 return <div><div className="mb-5 flex flex-wrap gap-3"><label className="min-w-0 flex-1"><span className="sr-only">Cari data</span><input type="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Cari data…" className="w-full rounded-full border border-[#EADFF2] bg-white px-5 py-3 text-sm focus:outline-purple-600"/></label>{filters.length>0&&<label><span className="sr-only">Filter status</span><select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}} className="rounded-full border border-[#EADFF2] bg-white px-4 py-3 text-sm"><option value="">Semua status</option>{filters.map(f=><option key={f.value} value={f.value}>{f.label}</option>)}</select></label>}</div><div className="overflow-x-auto rounded-2xl border border-[#EADFF2]"><table className="w-full text-left text-sm"><thead className="bg-lilac/60"><tr>{columns.map(c=><th scope="col" key={c.key} className="whitespace-nowrap px-4 py-3 font-medium">{c.label}</th>)}</tr></thead><tbody className="divide-y divide-[#EADFF2] bg-white">{visible.map(row=><tr key={rowKey(row)}>{columns.map(c=><td key={c.key} className="px-4 py-4">{c.render(row)}</td>)}</tr>)}{!visible.length&&<tr><td colSpan={columns.length} className="p-8 text-center text-muted">{empty}</td></tr>}</tbody></table></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs text-muted"><p>{filtered.length} data · halaman {current} / {pages}</p><div className="flex gap-2"><button type="button" disabled={current<=1} onClick={()=>setPage(current-1)} className="btn btn-ghost !px-4 !py-2 disabled:opacity-40">Sebelumnya</button><button type="button" disabled={current>=pages} onClick={()=>setPage(current+1)} className="btn btn-ghost !px-4 !py-2 disabled:opacity-40">Berikutnya</button></div></div></div>;
}
