"use client";
import {useRef,useState,useEffect} from "react";
import {useRouter} from "next/navigation";
import {educationInputError,educationSlug,youtubeId,type EducationKind,type EducationRecord} from "@/lib/education";
import {saveEducation,deleteEducation,changeEducationStatus,lookupYoutubeTitle} from "@/app/admin/(panel)/edukasi/actions";
import DataTable from "./DataTable";
import Modal from "./Modal";
import ConfirmDialog from "./ConfirmDialog";
import FormField from "./FormField";
import MediaPicker from "./MediaPicker";
import StatusBadge from "./StatusBadge";
import Toast from "./Toast";
const input="w-full rounded-2xl border border-[#EADFF2] bg-white p-3 text-sm focus:outline-purple-600";
const blank=():EducationRecord=>({id:"",title:"",category:"",status:"draft",is_premium:false,published_at:null,slug:"",excerpt:"",content:"",cover_url:"",youtube_url:"",description:"",sort:0});
export default function EducationManager({articles,videos,loadError}:{articles:EducationRecord[];videos:EducationRecord[];loadError:boolean}){
 const router=useRouter();const [kind,setKind]=useState<EducationKind>("videos");const [editing,setEditing]=useState<EducationRecord|null>(null);
 const [remove,setRemove]=useState<EducationRecord|null>(null);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState<{message:string;error:boolean}|null>(null);
 const [category,setCategory]=useState("");const [access,setAccess]=useState("");
 const rows=kind==="videos"?videos:articles;const categories=[...new Set(rows.map(r=>r.category))].sort();
 function notify(error:string|null,success:string){setNotice({message:error??success,error:Boolean(error)});if(!error)router.refresh();}
 async function status(item:EducationRecord){setBusy(true);try{notify((await changeEducationStatus(kind,item.id,item.status==="published"?"draft":"published")).error,"Status diperbarui.");}catch{notify("Status belum berubah. Coba lagi, ya.","");}finally{setBusy(false);}}
 return <div className="mt-7"><div role="group" aria-label="Jenis konten" className="flex flex-wrap gap-3">{([['videos','Video'],['articles','Artikel']] as const).map(([value,label])=><button type="button" key={value} aria-pressed={kind===value} className={`btn ${kind===value?"btn-brand":"btn-ghost"}`} onClick={()=>{setKind(value);setCategory("");setAccess("");}}>{label}</button>)}<button type="button" className="btn btn-brand ml-auto" onClick={()=>setEditing(blank())}>+ Tambah {kind==="videos"?"video":"artikel"}</button></div>
 {loadError&&<p role="alert" className="mt-5 rounded-2xl bg-peach p-4">Konten belum bisa dimuat. Pastikan migration sudah diterapkan.</p>}
 <div className="my-5 flex flex-wrap gap-3"><label className="text-sm">Kategori<select value={category} onChange={e=>setCategory(e.target.value)} className={`${input} mt-1`}><option value="">Semua kategori</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="text-sm">Akses<select value={access} onChange={e=>setAccess(e.target.value)} className={`${input} mt-1`}><option value="">Semua akses</option><option value="free">Gratis</option><option value="premium">Premium</option></select></label></div>
 <DataTable key={kind} rows={rows.filter(r=>(!category||r.category===category)&&(!access||r.is_premium===(access==="premium")))} rowKey={r=>r.id} searchText={r=>`${r.title} ${r.category} ${r.slug??""}`} filterText={r=>r.status} filters={[{value:"draft",label:"Draf"},{value:"published",label:"Tayang"},{value:"hidden",label:"Disembunyikan"}]} columns={[
 {key:"title",label:"Konten",render:r=><div className="flex min-w-52 items-center gap-3">{kind==="videos"&&r.youtube_id?<img src={`https://img.youtube.com/vi/${r.youtube_id}/hqdefault.jpg`} alt="" width={96} height={54} className="h-14 w-24 rounded-xl object-cover"/>:r.cover_url?<img src={r.cover_url} alt="" width={64} height={54} className="h-14 w-16 rounded-xl object-cover"/>:null}<div><p className="font-medium">{r.title}</p><p className="mt-1 text-xs text-muted">{r.category}{kind==="videos"?` · Urutan ${r.sort??0}`:""}</p></div></div>},
 {key:"status",label:"Status",render:r=><div><StatusBadge active={r.status==="published"} label={r.status==="published"?"Tayang":r.status==="draft"?"Draf":"Disembunyikan"}/>{r.published_at&&new Date(r.published_at)>new Date()&&<p className="mt-2 text-xs text-muted">Terjadwal: {new Date(r.published_at).toLocaleString("id-ID")}</p>}</div>},
 {key:"access",label:"Akses",render:r=>r.is_premium?"Premium":"Gratis"},
 {key:"actions",label:"Aksi",render:r=><div className="flex flex-wrap gap-2"><button type="button" className="btn btn-ghost text-xs" onClick={()=>setEditing({...r,status:r.status==="hidden"?"draft":r.status})}>Edit</button><button type="button" disabled={busy} className="btn btn-ghost text-xs" onClick={()=>status(r)}>{r.status==="published"?"Jadikan draf":"Terbitkan"}</button><button type="button" disabled={busy} className="btn btn-ghost text-xs text-red-700" onClick={()=>setRemove(r)}>Hapus</button></div>}
 ]} empty="Belum ada konten yang sesuai. Tambahkan konten pertama, ya."/>
 <Modal open={Boolean(editing)} title={`${editing?.id?"Edit":"Tambah"} ${kind==="videos"?"video":"artikel"}`} onClose={()=>{if(!busy)setEditing(null);}}>{editing&&<EducationForm key={`${kind}-${editing.id}`} kind={kind} initial={editing} busy={busy} onBusy={setBusy} onSave={error=>{notify(error,"Konten tersimpan.");if(!error)setEditing(null);}}/>}</Modal>
 <ConfirmDialog open={Boolean(remove)} title="Hapus konten?" description={`“${remove?.title??""}” akan dihapus. Tindakan ini tidak bisa dibatalkan.`} busy={busy} onCancel={()=>{if(!busy)setRemove(null);}} onConfirm={async()=>{if(!remove)return;setBusy(true);try{const result=await deleteEducation(kind,remove.id);notify(result.error,"Konten terhapus.");if(!result.error)setRemove(null);}catch{notify("Konten belum terhapus. Coba lagi, ya.","");}finally{setBusy(false);}}}/>
 {notice&&<Toast message={notice.message} error={notice.error} onClose={()=>setNotice(null)}/>}
 </div>;
}
function EducationForm({kind,initial,busy,onBusy,onSave}:{kind:EducationKind;initial:EducationRecord;busy:boolean;onBusy:(v:boolean)=>void;onSave:(error:string|null)=>void}){
 const [item,setItem]=useState(initial);const [error,setError]=useState<string|null>(null);const [lookup,setLookup]=useState(false);const [lookupMessage,setLookupMessage]=useState<string|null>(null);
 const body=useRef<HTMLTextAreaElement>(null);const latest=useRef(item);latest.current=item;const request=useRef(0);useEffect(()=>()=>{request.current++;},[]);
 const [slugEdited,setSlugEdited]=useState(Boolean(initial.id));
 function update<K extends keyof EducationRecord>(key:K,value:EducationRecord[K]){setItem(prev=>({...prev,[key]:value}));setError(null);}
 async function fetchTitle(){const url=item.youtube_url??"";if(!youtubeId(url)){setLookupMessage("Tempel link YouTube yang valid terlebih dahulu.");return;}const token=++request.current;const titleBefore=item.title;setLookup(true);setLookupMessage(null);try{const result=await lookupYoutubeTitle(url);if(token!==request.current||latest.current.youtube_url!==url)return;if(result.title&&latest.current.title===titleBefore)update("title",result.title);setLookupMessage(result.error??"Judul berhasil diambil.");}catch{if(token===request.current)setLookupMessage("Judul belum tersedia. Isi judul secara manual, ya.");}finally{if(token===request.current)setLookup(false);}}
 function format(open:string,close:string){const el=body.current;if(!el)return;const start=el.selectionStart,end=el.selectionEnd;const value=item.content??"";update("content",value.slice(0,start)+open+value.slice(start,end)+close+value.slice(end));requestAnimationFrame(()=>{el.focus();el.setSelectionRange(start+open.length,end+open.length);});}
 const videoId=youtubeId(item.youtube_url??"");
 const dateValue=item.published_at?(()=>{const date=new Date(item.published_at);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);})():"";
 return <form className="grid gap-5" onSubmit={async e=>{e.preventDefault();const validation=educationInputError(kind,item);if(validation){setError(validation);return;}onBusy(true);try{onSave((await saveEducation(kind,item)).error);}catch{setError("Konten belum tersimpan. Coba lagi, ya.");}finally{onBusy(false);}}}><fieldset disabled={busy} className="grid gap-5">
 {kind==="videos"&&<><FormField label="Link YouTube" htmlFor="education-url" hint="watch?v=, youtu.be/, shorts/, atau embed/ (HTTPS)."><input id="education-url" type="url" required maxLength={2000} value={item.youtube_url??""} onChange={e=>{update("youtube_url",e.target.value);request.current++;setLookup(false);}} onBlur={()=>{if(!latest.current.title.trim()&&youtubeId(latest.current.youtube_url??""))void fetchTitle();}} className={input}/></FormField><div><button type="button" disabled={lookup} onClick={()=>void fetchTitle()} className="btn btn-ghost text-xs">{lookup?"Mengambil judul…":"Ambil judul otomatis"}</button>{lookupMessage&&<p role="status" className="mt-2 text-xs text-muted">{lookupMessage}</p>}</div></>}
 <FormField label="Judul" htmlFor="education-title"><input id="education-title" required maxLength={200} value={item.title} onChange={e=>{update("title",e.target.value);if(kind==="articles"&&!slugEdited)update("slug",educationSlug(e.target.value));}} className={input}/></FormField>
 {kind==="articles"?<><FormField label="Slug" htmlFor="education-slug" hint="Terisi otomatis dari judul; harus unik."><input id="education-slug" required maxLength={180} value={item.slug??""} onChange={e=>{setSlugEdited(true);update("slug",e.target.value);}} className={input}/></FormField><FormField label="Ringkasan" htmlFor="education-excerpt"><textarea id="education-excerpt" rows={3} maxLength={1000} value={item.excerpt??""} onChange={e=>update("excerpt",e.target.value)} className={input}/></FormField>
 <div><label htmlFor="education-body" className="text-sm font-medium">Isi artikel</label><div role="group" aria-label="Format teks" className="my-2 flex flex-wrap gap-2">{[{label:"Tebal",open:"<strong>",close:"</strong>"},{label:"Miring",open:"<em>",close:"</em>"},{label:"Judul bagian",open:"<h2>",close:"</h2>"},{label:"Paragraf",open:"<p>",close:"</p>"},{label:"Daftar",open:"<ul><li>",close:"</li></ul>"},{label:"Kutipan",open:"<blockquote>",close:"</blockquote>"}].map(f=><button key={f.label} type="button" className="rounded-full bg-lilac px-3 py-2 text-xs" onClick={()=>format(f.open,f.close)}>{f.label}</button>)}</div><textarea ref={body} id="education-body" required rows={10} maxLength={100000} value={item.content??""} onChange={e=>update("content",e.target.value)} className={input} aria-describedby="education-format-hint"/><p id="education-format-hint" className="mt-2 text-xs text-muted">Pilih teks, lalu klik format. Tag HTML format dasar disimpan; skrip, atribut, dan embed dibuang di server.</p></div>
 <MediaPicker label="Gambar sampul" value={item.cover_url??""} onChange={url=>update("cover_url",url)}/>{item.cover_url&&<button type="button" className="btn btn-ghost justify-self-start text-xs" onClick={()=>update("cover_url","")}>Hapus sampul</button>}
 </>:<><FormField label="Deskripsi singkat" htmlFor="education-description"><textarea id="education-description" rows={3} maxLength={1000} value={item.description??""} onChange={e=>update("description",e.target.value)} className={input}/></FormField>{videoId&&<div className="grid gap-3 sm:grid-cols-[2fr_1fr]"><iframe src={`https://www.youtube-nocookie.com/embed/${videoId}`} title="Pratinjau video" className="aspect-video w-full rounded-2xl border-0" allow="encrypted-media; picture-in-picture; fullscreen" allowFullScreen/><img src={`https://img.youtube.com/vi/${videoId}/hqdefault.jpg`} alt="Thumbnail otomatis video" className="aspect-video w-full rounded-2xl object-cover"/></div>}</>}
 <div className="grid gap-4 sm:grid-cols-2"><FormField label="Kategori" htmlFor="education-category"><input id="education-category" required maxLength={80} value={item.category} onChange={e=>update("category",e.target.value)} className={input}/></FormField><FormField label="Status" htmlFor="education-status"><select id="education-status" value={item.status} onChange={e=>update("status",e.target.value as "draft"|"published")} className={input}><option value="draft">Draf</option><option value="published">Tayang</option></select></FormField>{kind==="videos"&&<FormField label="Urutan" htmlFor="education-sort"><input id="education-sort" type="number" min={0} max={100000} step={1} required value={item.sort??0} onChange={e=>update("sort",Number(e.target.value))} className={input}/></FormField>}<FormField label="Jadwal terbit" htmlFor="education-date" hint="Kosongkan untuk terbit sekarang; hanya tayang bila status Tayang."><input id="education-date" type="datetime-local" value={dateValue} onChange={e=>update("published_at",e.target.value?new Date(e.target.value).toISOString():null)} className={input}/></FormField></div>
 <label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={item.is_premium} onChange={e=>update("is_premium",e.target.checked)} className="h-5 w-5 accent-purple-600"/>Hanya untuk pengguna Premium</label>
 {error&&<p role="alert" className="rounded-2xl bg-peach p-4 text-sm">{error}</p>}<button type="submit" className="btn btn-brand justify-self-start">{busy?"Menyimpan…":"Simpan konten →"}</button>
 </fieldset></form>;
}
