"use client";
import {useEffect,useRef,useState} from "react";
import {listMedia,saveMediaAlt,deleteMedia} from "@/app/admin/(panel)/media/actions";
import type {MediaItem} from "@/lib/admin-types";
import {resizeImage} from "./image-resize";
import ConfirmDialog from "./ConfirmDialog";
import Toast from "./Toast";
type Listing={rows:MediaItem[];total:number;error:string|null};
function MediaCard({item,picking,busy,onPick,onDelete,onSave,onMessage}:{item:MediaItem;picking:boolean;busy:boolean;onPick?:(item:MediaItem)=>void;onDelete:()=>void;onSave:(alt:string)=>void;onMessage:(text:string,error?:boolean)=>void}){
 const [alt,setAlt]=useState(item.alt);useEffect(()=>setAlt(item.alt),[item.alt]);
 async function copy(){try{await navigator.clipboard.writeText(item.url);onMessage("URL gambar disalin.");}catch{onMessage("URL belum bisa disalin. Buka gambar untuk menyalinnya.",true);}}
 return <article className="min-w-0 rounded-2xl border border-[#EADFF2] bg-white p-3">{picking?<button type="button" disabled={busy||item.deleting} onClick={()=>onPick?.(item)} aria-label={`Pilih ${item.alt||item.name||"gambar"}`} className="block aspect-square w-full overflow-hidden rounded-xl bg-lilac/40 focus-visible:outline-purple-600"><img src={item.url} alt={item.alt||"Gambar di media library"} loading="eager" className="h-full w-full object-contain"/></button>:<div className="aspect-square w-full overflow-hidden rounded-xl bg-lilac/40"><img src={item.url} alt={item.alt||"Gambar di media library"} loading="lazy" className="h-full w-full object-contain"/></div>}<p className="mt-3 truncate text-xs font-medium" title={item.name}>{item.name||"Gambar"}</p><p className="mt-1 text-[10px] text-muted">{Math.ceil(item.size/1024)} KB{item.deleting?" · Penghapusan perlu diselesaikan":""}</p>{picking?<button type="button" disabled={busy||item.deleting} onClick={()=>onPick?.(item)} className="btn btn-ghost mt-3 w-full justify-center !px-3 !py-2 text-xs disabled:opacity-40">Pilih gambar</button>:<><label htmlFor={`alt-${item.id}`} className="mb-1 mt-3 block text-xs">Alt text</label><input id={`alt-${item.id}`} value={alt} onChange={e=>setAlt(e.target.value)} maxLength={300} disabled={busy||item.deleting} className="w-full rounded-xl border border-[#EADFF2] px-3 py-2 text-xs focus:outline-purple-600"/><div className="mt-2 flex flex-wrap gap-2"><button type="button" disabled={busy||item.deleting||alt===item.alt} onClick={()=>onSave(alt)} className="rounded-full bg-lilac px-3 py-2 text-xs disabled:opacity-40">Simpan alt</button><button type="button" onClick={()=>void copy()} className="rounded-full bg-sage px-3 py-2 text-xs">Salin URL</button><button type="button" disabled={busy} onClick={onDelete} className="rounded-full bg-peach px-3 py-2 text-xs text-red-700 disabled:opacity-40">Hapus</button></div></>}</article>;
}
export default function MediaLibrary({initial,onPick}:{initial?:Listing;onPick?:(item:MediaItem)=>void}){
 const [listing,setListing]=useState<Listing>(initial??{rows:[],total:0,error:null});const [search,setSearch]=useState("");const [page,setPage]=useState(1);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(!initial);const [notice,setNotice]=useState({message:"",error:false});const [deleting,setDeleting]=useState<MediaItem|null>(null);const [drag,setDrag]=useState(false);const generation=useRef(0);
 const message=(text:string,error=false)=>setNotice({message:text,error});
 async function reload(){const ticket=++generation.current;setLoading(true);try{const result=await listMedia(search,page);if(ticket===generation.current){setListing(result);if(page>1&&!result.rows.length&&!result.error)setPage(page-1);}}catch{if(ticket===generation.current)message("Library belum bisa dimuat.",true);}finally{if(ticket===generation.current)setLoading(false);}}
 useEffect(()=>{const timer=setTimeout(()=>void reload(),200);return()=>{clearTimeout(timer);generation.current++;};},[search,page]);
 async function upload(files:FileList|File[]|null){if(!files?.length||busy)return;const batch=Array.from(files);if(batch.length>20){message("Unggah maksimal 20 gambar sekaligus.",true);return;}setBusy(true);let success=0;const errors:string[]=[];
 try{for(const file of batch){try{const resized=await resizeImage(file);const form=new FormData();form.set("image",resized);form.set("name",file.name);const response=await fetch("/admin/media/upload",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error??"Unggahan gagal.");success++;}catch(error){errors.push(`${file.name}: ${error instanceof Error&&!["TypeError","SyntaxError"].includes(error.name)?error.message:"Unggahan gagal. Periksa koneksi atau masuk ulang ke admin."}`);}}await reload();message(`${success} gambar diunggah.${errors.length?` ${errors.length} gagal. ${errors[0]}`:""}`,Boolean(errors.length));}finally{setBusy(false);}}
 async function save(item:MediaItem,alt:string){setBusy(true);try{const result=await saveMediaAlt(item.id,alt);message(result.error??"Alt text tersimpan.",Boolean(result.error));if(!result.error)await reload();}catch{message("Alt belum tersimpan.",true);}finally{setBusy(false);}}
 async function remove(){if(!deleting)return;setBusy(true);try{const result=await deleteMedia(deleting.id);message(result.error??"Gambar dihapus.",Boolean(result.error));if(!result.error)setDeleting(null);await reload();}catch{message("Gambar belum terhapus.",true);}finally{setBusy(false);}}
 return <div><div onDragOver={e=>{e.preventDefault();if(!busy)setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);void upload(e.dataTransfer.files);}} className={`mb-6 rounded-2xl border-2 border-dashed p-5 text-center ${drag?"border-purple-600 bg-lilac":"border-[#EADFF2] bg-[#FBF8FD]"}`}><p className="text-sm font-medium">{busy?"Memproses gambar…":"Tarik gambar ke sini atau pilih berkas"}</p><p className="mt-2 text-xs text-muted">JPG, PNG, WebP · maks. 5 MB per gambar · resize hingga 1600 px.</p><label className="mt-4 inline-block cursor-pointer rounded-full bg-lilac px-5 py-3 text-xs text-purple-800 focus-within:outline focus-within:outline-2 focus-within:outline-purple-600">Pilih gambar<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy} className="sr-only" onChange={e=>{void upload(e.target.files);e.target.value="";}}/></label></div><label><span className="sr-only">Cari gambar</span><input type="search" value={search} maxLength={120} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Cari nama gambar atau alt text…" className="mb-5 w-full rounded-full border border-[#EADFF2] px-5 py-3 text-sm focus:outline-purple-600"/></label>{listing.error&&<p role="alert" className="mb-4 text-sm text-red-700">{listing.error}</p>}<div aria-busy={loading} className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-4">{listing.rows.map(item=><MediaCard key={item.id} item={item} picking={Boolean(onPick)} busy={busy} onPick={onPick} onDelete={()=>setDeleting(item)} onSave={alt=>void save(item,alt)} onMessage={message}/>)}</div>{!listing.rows.length&&!listing.error&&<p role="status" className="py-8 text-center text-sm text-muted">{loading?"Memuat gambar…":"Belum ada gambar. Unggah gambar pertamamu."}</p>}<div className="mt-5 flex flex-wrap items-center justify-between gap-3 text-xs text-muted"><p>{listing.total} gambar · halaman {page} / {Math.max(1,Math.ceil(listing.total/24))}</p><div className="flex gap-2"><button type="button" disabled={busy||loading||page<=1} onClick={()=>setPage(page-1)} className="btn btn-ghost !px-3 !py-2 disabled:opacity-40">Sebelumnya</button><button type="button" disabled={busy||loading||page*24>=listing.total} onClick={()=>setPage(page+1)} className="btn btn-ghost !px-3 !py-2 disabled:opacity-40">Berikutnya</button></div></div><ConfirmDialog open={Boolean(deleting)} title="Hapus gambar?" description="Gambar yang masih dipakai tidak dapat dihapus. File dan metadata akan dihapus permanen." busy={busy} onCancel={()=>setDeleting(null)} onConfirm={()=>void remove()}/><Toast {...notice} onClose={()=>message("")}/></div>;
}
