"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import DataTable from "./DataTable";
import MediaPicker from "./MediaPicker";
import ConfirmDialog from "./ConfirmDialog";
import Toast from "./Toast";
import {seoScore,type SeoSettings,type SeoDocument,type SeoMeta,type SeoRedirect} from "@/lib/seo-schema";
import {saveGlobalSeo,saveDocumentSeo,saveSeoRedirect,deleteSeoRedirect} from "@/app/admin/(panel)/seo/actions";
const input="mt-2 w-full rounded-2xl border border-[#EADFF2] bg-white px-4 py-3 text-sm focus:outline-purple-600";
const blankRedirect:SeoRedirect={id:'',source:'',destination:'',active:true};
export default function SeoManager({settings,documents,redirects,loadError}:{settings:SeoSettings;documents:SeoDocument[];redirects:SeoRedirect[];loadError:boolean}){const router=useRouter(),[tab,setTab]=useState('global'),[global,setGlobal]=useState(settings),[selected,setSelected]=useState<SeoDocument|null>(documents[0]??null),[meta,setMeta]=useState<SeoMeta>(documents[0]?.meta??{title:'',description:'',canonical:'',ogImage:'',noindex:false}),[redirect,setRedirect]=useState(blankRedirect),[deleting,setDeleting]=useState<string|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState<{message:string;error:boolean}|null>(null);
async function run(task:()=>Promise<{error:string|null}>){if(busy)return;setBusy(true);try{const r=await task();setNotice({message:r.error??'Perubahan tersimpan dan tercatat di audit log.',error:Boolean(r.error)});if(!r.error){setDeleting(null);router.refresh();}}catch{setNotice({message:'Perubahan belum tersimpan. Coba lagi.',error:true});}finally{setBusy(false);}}
function choose(d:SeoDocument){setSelected(d);setMeta(d.meta);}
const effective={...meta,title:meta.title||selected?.title||'',description:meta.description||global.description,ogImage:meta.ogImage||global.ogImage};const previewTitle=global.titleTemplate.replaceAll('%s',effective.title),previewUrl=meta.canonical||((global.canonicalBase||'https://domain-situs')+(selected?.path??'/'));
return <div><h1 className="text-3xl font-medium">SEO situs</h1><p className="mt-3 text-sm text-muted">Atur tampilan hasil pencarian, kartu share, dan redirect permanen.</p>{loadError&&<p role="alert" className="mt-4 rounded-2xl bg-peach p-4 text-sm">Sebagian data belum dimuat. Terapkan migration dan muat ulang sebelum menyimpan.</p>}<div role="tablist" aria-label="Pengaturan SEO" className="my-6 flex flex-wrap gap-2">{[['global','Global'],['robots','robots.txt'],['pages','Halaman'],['redirects','Redirect 301']].map(([v,t])=><button key={v} role="tab" id={`seo-tab-${v}`} aria-controls={`seo-panel-${v}`} aria-selected={tab===v} onClick={()=>setTab(v)} type="button" className={`btn text-xs ${tab===v?'btn-brand':'btn-ghost'}`}>{t}</button>)}</div><section role="tabpanel" id={`seo-panel-${tab}`} aria-labelledby={`seo-tab-${tab}`}><fieldset disabled={busy||loadError} className="min-w-0 disabled:opacity-60">
{(tab==='global'||tab==='robots')&&<form onSubmit={e=>{e.preventDefault();void run(()=>saveGlobalSeo(global));}} className="grid max-w-3xl gap-5 rounded-[28px] bg-white p-6 shadow-soft">{tab==='global'?<>{([['titleTemplate','Template judul (%s = judul halaman)'],['description','Deskripsi default'],['canonicalBase','Canonical base URL (HTTPS, domain tanpa path)'],['googleVerification','Kode verifikasi Google'],['bingVerification','Kode verifikasi Bing'],['analyticsId','ID Google Analytics 4']] as const).map(([k,l])=><label key={k} className="text-sm">{l}{k==='description'?<textarea maxLength={500} rows={4} className={input} value={global[k]} onChange={e=>setGlobal({...global,[k]:e.target.value})}/>:<input maxLength={k==='canonicalBase'?2048:200} className={input} value={global[k]} onChange={e=>setGlobal({...global,[k]:e.target.value})}/>}</label>)}<MediaPicker label="Gambar OG default" value={global.ogImage} onChange={ogImage=>setGlobal({...global,ogImage})}/><button type="button" onClick={()=>setGlobal({...global,ogImage:''})} className="text-left text-xs underline">Kosongkan gambar OG</button></>:<><label className="text-sm">Isi robots.txt<textarea rows={16} maxLength={10000} value={global.robots} onChange={e=>setGlobal({...global,robots:e.target.value})} className={`${input} font-mono`}/></label><p className="text-xs text-muted">Dukung User-agent, Allow, Disallow, Crawl-delay, Sitemap, Host dan komentar (#). Disallow area /app, /admin, /auth tetap ditambahkan untuk setiap bot. Komentar tidak muncul pada hasil akhir. Sitemap ditambahkan otomatis bila domain tersedia.</p></>}<button type="submit" className="btn btn-brand justify-self-start">{busy?'Menyimpan…':'Simpan pengaturan'}</button></form>}
{tab==='pages'&&<div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><DataTable rows={documents} rowKey={d=>d.path} searchText={d=>d.title+' '+d.path} columns={[{key:'page',label:'Halaman / Artikel',render:d=><button type="button" aria-pressed={selected?.path===d.path} onClick={()=>choose(d)} className="text-left"><strong>{d.title}</strong><span className="block text-xs text-muted">{d.path} · {d.published?'Tayang':'Draft'}</span></button>},{key:'meta',label:'Meta title',render:d=>d.meta.title||'Default'}]}/>{selected&&<form onSubmit={e=>{e.preventDefault();void run(()=>saveDocumentSeo(selected.path,meta));}} className="grid gap-5 rounded-[28px] bg-white p-6 shadow-soft"><h2 className="text-lg font-medium">{selected.title}</h2><p className="text-xs text-muted">{selected.path}</p>{(['title','description','canonical'] as const).map(k=><label key={k} className="text-sm">{k==='title'?'Meta title':k==='description'?'Meta description':'Canonical (HTTPS)'}{k==='description'?<textarea rows={4} maxLength={500} value={meta[k]} onChange={e=>setMeta({...meta,[k]:e.target.value})} className={input}/>:<input maxLength={k==='title'?200:2048} value={meta[k]} onChange={e=>setMeta({...meta,[k]:e.target.value})} className={input}/>} {k!=='canonical'&&<span className="mt-1 block text-xs text-muted">{meta[k].length} karakter · saran {k==='title'?'30–60':'120–160'}</span>}</label>)}<MediaPicker label="Gambar OG halaman" value={meta.ogImage} onChange={ogImage=>setMeta({...meta,ogImage})}/><button type="button" className="text-left text-xs underline" onClick={()=>setMeta({...meta,ogImage:''})}>Gunakan gambar default</button><label className="flex gap-3 text-sm"><input type="checkbox" checked={meta.noindex} onChange={e=>setMeta({...meta,noindex:e.target.checked})}/>Noindex (jangan tampil di mesin pencari)</label><div className="rounded-2xl bg-lilac/40 p-4"><p className="text-xs font-medium">Skor sederhana: {seoScore(selected,effective)}/100</p><p className="mt-2 text-xs text-muted">Judul 25 · deskripsi 25 · heading 20 · alt gambar 15 · gambar OG 15. Indikator ini bukan jaminan peringkat.</p></div><div className="min-w-0 rounded-2xl border border-[#EADFF2] p-4"><p className="text-xs text-muted">Preview Google</p><p className="mt-2 truncate text-xs">{previewUrl}</p><p className="mt-2 line-clamp-2 text-xl text-purple-800">{previewTitle}</p><p className="mt-2 line-clamp-3 text-sm text-muted">{effective.description}</p></div><div className="overflow-hidden rounded-2xl border border-[#EADFF2]">{effective.ogImage&&<img src={effective.ogImage} alt="Preview gambar share" className="aspect-[1.91] w-full object-cover"/>}<div className="p-4"><p className="text-xs text-muted">Preview kartu share</p><p className="mt-2 font-medium">{previewTitle}</p><p className="mt-2 line-clamp-2 text-sm text-muted">{effective.description}</p></div></div><button type="submit" className="btn btn-brand justify-self-start">Simpan metadata</button></form>}</div>}
{tab==='redirects'&&<div className="grid gap-6 xl:grid-cols-2"><div><button type="button" className="btn btn-brand mb-4 text-xs" onClick={()=>setRedirect(blankRedirect)}>+ Redirect baru</button><DataTable rows={redirects} rowKey={r=>r.id} searchText={r=>r.source+' '+r.destination} columns={[{key:'src',label:'Asal → tujuan',render:r=><div className="max-w-xs break-all"><strong>{r.source}</strong><p>{r.destination}</p><small>{r.active?'Aktif':'Nonaktif'}</small></div>},{key:'act',label:'Aksi',render:r=><div className="flex gap-2"><button type="button" className="btn btn-ghost text-xs" onClick={()=>setRedirect(r)}>Edit</button><button type="button" className="btn btn-ghost text-xs" onClick={()=>setDeleting(r.id)}>Hapus</button></div>}]}/></div><form onSubmit={e=>{e.preventDefault();void run(()=>saveSeoRedirect(redirect));}} className="grid content-start gap-5 rounded-[28px] bg-white p-6 shadow-soft"><h2 className="text-lg font-medium">{redirect.id?'Edit':'Tambah'} redirect 301</h2><label className="text-sm">Alamat asal (/halaman-lama)<input required maxLength={180} value={redirect.source} onChange={e=>setRedirect({...redirect,source:e.target.value})} className={input}/></label><label className="text-sm">Tujuan (/halaman-baru atau HTTPS)<input required maxLength={2048} value={redirect.destination} onChange={e=>setRedirect({...redirect,destination:e.target.value})} className={input}/></label><label className="flex gap-3 text-sm"><input type="checkbox" checked={redirect.active} onChange={e=>setRedirect({...redirect,active:e.target.checked})}/>Aktif</label><button type="submit" className="btn btn-brand justify-self-start">Simpan redirect</button></form></div>}
</fieldset></section><ConfirmDialog open={Boolean(deleting)} title="Hapus redirect?" description="Alamat lama akan berhenti dialihkan." busy={busy} onCancel={()=>setDeleting(null)} onConfirm={()=>{if(deleting)void run(()=>deleteSeoRedirect(deleting));}}/>{notice&&<Toast {...notice} onClose={()=>setNotice(null)}/>}</div>;}
