"use client";
import {useState,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {DEFAULT_SITE_SETTINGS,validateSiteSettings,type SiteSettings} from "@/lib/site-settings-schema";
import {saveSiteSettings} from "@/app/admin/(panel)/pengaturan/actions";
import MediaPicker from "./MediaPicker";
import FormField from "./FormField";
import Toast from "./Toast";
const inputClass="w-full rounded-xl border border-[#EADFF2] bg-white px-4 py-3 text-sm focus:outline-purple-600";
const sectionClass="space-y-5 rounded-[24px] border border-[#EADFF2] bg-[#FBF8FD] p-5 sm:p-6";
export default function SiteSettingsForm({initial,loadError}:{initial:SiteSettings;loadError:boolean}){
 const router=useRouter();const [values,setValues]=useState(initial);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState({message:"",error:false});
 function update<K extends keyof SiteSettings>(key:K,value:SiteSettings[K]){setValues(old=>({...old,[key]:value}));}
 async function submit(event:FormEvent){event.preventDefault();const normalized={...values,chips:values.chips.map(v=>v.trim()).filter(Boolean)};const invalid=validateSiteSettings(normalized);if(invalid){setNotice({message:invalid,error:true});return;}setBusy(true);try{const result=await saveSiteSettings(normalized);setNotice({message:result.error??"Pengaturan situs tersimpan.",error:Boolean(result.error)});if(!result.error)router.refresh();}catch{setNotice({message:"Pengaturan belum tersimpan. Periksa koneksi.",error:true});}finally{setBusy(false);}}
 return <>{loadError&&<p role="alert" className="mb-5 text-sm text-red-700">Pengaturan belum bisa dimuat. Muat ulang sebelum menyimpan.</p>}<form onSubmit={submit}><fieldset disabled={busy||loadError} className="space-y-6"><section className={sectionClass}><h2 className="text-lg font-medium">Identitas situs</h2><FormField label="Nama situs" htmlFor="site-name"><input id="site-name" value={values.name} onChange={e=>update("name",e.target.value)} required maxLength={80} className={inputClass}/></FormField><div className="grid gap-6 sm:grid-cols-2"><div><MediaPicker label="Logo" value={values.logoUrl} onChange={url=>update("logoUrl",url)}/><button type="button" onClick={()=>update("logoUrl",DEFAULT_SITE_SETTINGS.logoUrl)} className="mt-3 text-xs text-purple-800 underline">Pakai logo bawaan</button></div><div><MediaPicker label="Favicon" value={values.faviconUrl} onChange={url=>update("faviconUrl",url)}/><button type="button" onClick={()=>update("faviconUrl",DEFAULT_SITE_SETTINGS.faviconUrl)} className="mt-3 text-xs text-purple-800 underline">Pakai favicon bawaan</button></div></div></section>
 <section className={sectionClass}><h2 className="text-lg font-medium">Kontak & WhatsApp</h2><div className="grid gap-5 sm:grid-cols-2"><FormField label="Nomor WhatsApp" htmlFor="site-whatsapp" hint="Sertakan kode negara, contoh format: 62…"><input id="site-whatsapp" type="tel" value={values.whatsappNumber} onChange={e=>update("whatsappNumber",e.target.value)} required maxLength={30} className={inputClass}/></FormField><FormField label="Email kontak" htmlFor="site-email"><input id="site-email" type="email" value={values.contactEmail} onChange={e=>update("contactEmail",e.target.value)} maxLength={254} className={inputClass}/></FormField></div><FormField label="Teks sapaan WhatsApp" htmlFor="site-greeting"><textarea id="site-greeting" value={values.whatsappGreeting} onChange={e=>update("whatsappGreeting",e.target.value)} required maxLength={1000} rows={3} className={inputClass}/></FormField><div><h3 className="mb-3 text-sm font-medium">Sosial media</h3><div className="space-y-3">{values.socials.map((social,index)=><div key={index} className="grid items-end gap-3 sm:grid-cols-[1fr_2fr_auto]"><FormField label={`Nama sosmed ${index+1}`} htmlFor={`social-name-${index}`}><input id={`social-name-${index}`} value={social.label} onChange={e=>update("socials",values.socials.map((v,i)=>i===index?{...v,label:e.target.value}:v))} required maxLength={50} className={inputClass}/></FormField><FormField label="URL HTTPS" htmlFor={`social-url-${index}`}><input id={`social-url-${index}`} type="url" value={social.url} onChange={e=>update("socials",values.socials.map((v,i)=>i===index?{...v,url:e.target.value}:v))} required maxLength={2048} className={inputClass}/></FormField><button type="button" onClick={()=>update("socials",values.socials.filter((_,i)=>i!==index))} aria-label={`Hapus sosmed ${index+1}`} className="rounded-full bg-peach px-4 py-3 text-sm">Hapus</button></div>)}</div><button type="button" disabled={values.socials.length>=12} onClick={()=>update("socials",[...values.socials,{label:"",url:""}])} className="btn btn-ghost mt-4 text-xs">Tambah sosmed +</button></div></section>
 <section className={sectionClass}><h2 className="text-lg font-medium">Landing & footer</h2><div className="grid gap-5 sm:grid-cols-3">{([{key:"users",label:"Jumlah pengguna"},{key:"stories",label:"Jumlah cerita"},{key:"articles",label:"Jumlah artikel / video"}] as const).map(stat=><FormField key={stat.key} label={stat.label} htmlFor={`stat-${stat.key}`} hint="Kosong berarti memakai teks bawaan."><input id={`stat-${stat.key}`} type="number" min={0} max={1000000000} step={1} value={values.stats[stat.key]??""} onChange={e=>update("stats",{...values.stats,[stat.key]:e.target.value===""?null:Number(e.target.value)})} className={inputClass}/></FormField>)}</div><FormField label="Chip gerakan" htmlFor="site-chips" hint="Satu chip per baris; urutan mengikuti daftar ini."><textarea id="site-chips" rows={6} value={values.chips.join("\n")} onChange={e=>update("chips",e.target.value.split("\n"))} className={inputClass}/></FormField><FormField label="Teks footer" htmlFor="site-footer"><textarea id="site-footer" rows={3} value={values.footerText} onChange={e=>update("footerText",e.target.value)} maxLength={1000} className={inputClass}/></FormField></section>
 <section className={sectionClass}><h2 className="text-lg font-medium">Bantuan darurat</h2><FormField label="Pesan bantuan" htmlFor="emergency-text"><textarea id="emergency-text" value={values.emergencyText} onChange={e=>update("emergencyText",e.target.value)} maxLength={1500} required rows={3} className={inputClass}/></FormField><div className="space-y-5">{values.emergencyContacts.map((contact,index)=><div key={index} className="space-y-3 rounded-2xl bg-white p-4"><div className="grid gap-3 sm:grid-cols-2"><FormField label={`Nama layanan ${index+1}`} htmlFor={`help-name-${index}`}><input id={`help-name-${index}`} value={contact.label} onChange={e=>update("emergencyContacts",values.emergencyContacts.map((v,i)=>i===index?{...v,label:e.target.value}:v))} required maxLength={80} className={inputClass}/></FormField><FormField label="Nomor / keterangan kontak" htmlFor={`help-phone-${index}`}><input id={`help-phone-${index}`} value={contact.phone} onChange={e=>update("emergencyContacts",values.emergencyContacts.map((v,i)=>i===index?{...v,phone:e.target.value}:v))} maxLength={40} className={inputClass}/></FormField></div><FormField label="Tautan HTTPS atau tel:" htmlFor={`help-url-${index}`}><input id={`help-url-${index}`} value={contact.url} onChange={e=>update("emergencyContacts",values.emergencyContacts.map((v,i)=>i===index?{...v,url:e.target.value}:v))} required maxLength={2048} className={inputClass}/></FormField><button type="button" onClick={()=>update("emergencyContacts",values.emergencyContacts.filter((_,i)=>i!==index))} className="text-xs text-red-700 underline">Hapus kontak ini</button></div>)}</div><button type="button" disabled={values.emergencyContacts.length>=10} onClick={()=>update("emergencyContacts",[...values.emergencyContacts,{label:"",phone:"",url:""}])} className="btn btn-ghost text-xs">Tambah kontak bantuan +</button></section><button className="btn btn-brand disabled:opacity-60" disabled={busy||loadError}>{busy?"Menyimpan…":"Simpan pengaturan →"}</button></fieldset></form><Toast {...notice} onClose={()=>setNotice({message:"",error:false})}/></>;
}
