create table profiles(id uuid primary key references auth.users on delete cascade, display_name text, avatar_url text, role text not null default 'user', premium_until timestamptz, created_at timestamptz default now());
create table stories(id uuid primary key default gen_random_uuid(), author_id uuid references profiles, alias text, body text not null, tags text[], status text default 'published', created_at timestamptz default now());
create table mood_entries(id uuid primary key default gen_random_uuid(), user_id uuid references profiles not null, day date not null, score int check(score between 1 and 5), emotions text[], note text, unique(user_id,day));
create table journal_entries(id uuid primary key default gen_random_uuid(), user_id uuid references profiles not null, title text, content text, mood_score int, created_at timestamptz default now());
create table plans(id uuid primary key default gen_random_uuid(), name text, price_idr int, period text, features text[], is_active bool default true);
create table payment_settings(id int primary key default 1, qris_image_url text, merchant_name text, instructions text, expiry_minutes int default 60);
create table orders(id uuid primary key default gen_random_uuid(), user_id uuid references profiles, plan_id uuid references plans, total_amount int, status text default 'pending', proof_url text, created_at timestamptz default now());
create table reviews(id uuid primary key default gen_random_uuid(), user_id uuid references profiles unique, rating int check(rating between 1 and 5), body text, status text default 'published', is_featured bool default false, created_at timestamptz default now());
create or replace function is_admin() returns bool language sql security definer as $$ select exists(select 1 from profiles where id=auth.uid() and role='admin') $$;
alter table profiles enable row level security; alter table stories enable row level security; alter table mood_entries enable row level security; alter table journal_entries enable row level security; alter table orders enable row level security; alter table reviews enable row level security; alter table plans enable row level security; alter table payment_settings enable row level security;
create policy own_profile on profiles for all using(id=auth.uid() or is_admin());
create policy own_mood on mood_entries for all using(user_id=auth.uid());
create policy own_journal on journal_entries for all using(user_id=auth.uid());
create policy own_orders on orders for all using(user_id=auth.uid() or is_admin());
create policy read_stories on stories for select using(status='published' or is_admin());
create policy read_reviews on reviews for select using(status='published' or user_id=auth.uid() or is_admin());
create policy write_reviews on reviews for insert with check(user_id=auth.uid());
create policy admin_reviews on reviews for update using(is_admin());
create policy read_plans on plans for select using(is_active or is_admin());
create policy admin_plans on plans for all using(is_admin());
create policy read_pay on payment_settings for select using(true);
create policy admin_pay on payment_settings for all using(is_admin());
